package backingform.validator;

import java.util.Arrays;

import model.donationbatch.DonationBatch;

import org.apache.commons.lang3.StringUtils;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;
import org.springframework.validation.Validator;

import viewmodel.DonationBatchViewModel;
import backingform.DonationBatchBackingForm;
import backingform.FindDonationBatchBackingForm;
import controller.UtilController;

public class DonationBatchBackingFormValidator implements Validator {

  private Validator validator;

  private UtilController utilController;

  public DonationBatchBackingFormValidator(Validator validator, UtilController utilController) {
    super();
    this.validator = validator;
    this.utilController = utilController;
  }

  @SuppressWarnings("unchecked")
  @Override
  public boolean supports(Class<?> clazz) {
    return Arrays.asList(DonationBatchBackingForm.class,
        FindDonationBatchBackingForm.class, DonationBatch.class,
        DonationBatchViewModel.class).contains(clazz);
  }

  @Override
  public void validate(Object obj, Errors errors) {
    if (obj == null || validator == null)
      return;
    ValidationUtils.invokeValidator(validator, obj, errors);
    DonationBatchBackingForm form = (DonationBatchBackingForm) obj;
    updateAutoGeneratedFields(form);
    if (utilController.isDuplicateDonationBatchNumber(form.getDonationBatch()))
      errors.rejectValue("donationBatch.batchNumber", "batchNumber.nonunique",
          "There exists a collection batch with the same batch number.");

    utilController.commonFieldChecks(form, "donationBatch", errors);
  }

  private void updateAutoGeneratedFields(DonationBatchBackingForm form) {
    if (StringUtils.isBlank(form.getBatchNumber()) &&
        utilController.isFieldAutoGenerated("donationBatch", "batchNumber")) {
      form.setBatchNumber(utilController.getNextBatchNumber());
    }
  }

}
