#!/bin/bash

set -o errexit
set -o nounset

cd /opt/bsis
mvn clean install -Dmaven.test.skip=true

# Stop tomcat
sudo service tomcat7 stop

# Remove the deployed version of bsis
sudo rm -rf /var/lib/tomcat7/webapps/{bsis.war,bsis}

# Deploy the war
sudo cp /opt/bsis/target/bsis.war /var/lib/tomcat7/webapps/

# Restart tomcat
sudo service tomcat7 start
