<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<%!public long getCurrentTime() {
		return System.nanoTime();
	}%>

<c:set var="unique_page_id"><%=getCurrentTime()%></c:set>
<c:set var="tabContentId">tabContent-${unique_page_id}</c:set>
<c:set var="mainContentId">mainContent-${unique_page_id}</c:set>
<c:set var="childContentId">childContent-${unique_page_id}</c:set>

<c:set var="addDonorFormId">addDonorForm-${unique_page_id}</c:set>

<c:set var="genderSelectorId">genderSelector-${unique_page_id}</c:set>

<script>
  $(document).ready(
      function() {

        function notifyParentSuccess() {
					 // let the parent know we are done
				   $("#${tabContentId}").parent().trigger("editDonorSuccess");
    		}

        function notifyParentCancel() {
					 // let the parent know we are done
				   $("#${tabContentId}").parent().trigger("editDonorCancel");
	   		}

        $("#${mainContentId}").find(".addDonorButton").button({
          icons : {
            primary : 'ui-icon-plusthick'
          }
        }).click(
            function() {
                addNewDonor($("#${addDonorFormId}")[0], "${tabContentId}", notifyParentSuccess);
            });

        $("#${mainContentId}").find(".clearFormButton").button({
          icons : {
            
          }
        }).click(refetchForm);

        function refetchForm() {
          $.ajax({
            url: "${refreshUrl}",
            data: {},
            type: "GET",
            success: function (response) {
              			 	 $("#${tabContentId}").replaceWith(response);
            				 },
            error:   function (response) {
											 showErrorMessage("Something went wrong. Please try again.");
            				 }
            
          });
        }

        $("#${genderSelectorId}").multiselect({
          multiple : false,
          selectedList : 1,
          header : false
        });

        $("#${addDonorFormId}").find(".birthDate").datepicker({
          changeMonth : true,
          changeYear : true,
          minDate : -36500,
          maxDate : 0,
          dateFormat : "mm/dd/yy",
          yearRange : "c-100:c0",
        });

        if ("${firstTimeRender}" == "true") {
          $("#${mainContentId}").find('textarea[name="address"]').html("${donorFields.address.defaultValue}");
        	$("#${mainContentId}").find('textarea[name="notes"]').html("${donorFields.notes.defaultValue}");
        	setDefaultValueForSelector(getGenderSelector(), "${donorFields.gender.defaultValue}");
        }

        function getGenderSelector() {
          return $("#${mainContentId}").find('select[name="gender"]').multiselect();
        }

        function updateBarcode(val) {
            if (val === null || val === undefined || val === "")
              val = "-";
  	        $("#${addDonorFormId}").find(".barcodeContainer").barcode(
  						  val,
  							"code128",
  							{barWidth: 2, barHeight: 50, fontSize: 15, output: "css"});
          }
          updateBarcode("${addDonorForm.donor.donorNumber}");

          $("#${addDonorFormId}").find('input[name="donorNumber"]').keyup(function() {
            updateBarcode($(this).val());
          });

      });
</script>

<div id="${tabContentId}">
	<div id="${mainContentId}">
		<c:if test="${!empty success && !success}">
			<div class="errorBox ui-state-highlight">
				<jsp:include page="../common/errorIcon.jsp"/> Error adding donor. Please fix the errors noted below.
			</div>
		</c:if>
		<form:form id="${addDonorFormId}" method="POST" class="formInTabPane"
			commandName="addDonorForm">
			<form:hidden path="id" />
			<c:if test="${donorFields.donorNumber.autoGenerated}">
				<div class="barcodeContainer"></div>
				<c:if test="${donorFields.donorNumber.hidden != true }">
					<div>
						<form:label path="donorNumber">${donorFields.donorNumber.displayName}</form:label>
						<form:input path="donorNumber" value="${donorFields.donorNumber.defaultValue}" />
						<form:errors class="formError" path="donor.donorNumber" delimiter=", "></form:errors>
					</div>
				</c:if>
			</c:if>
			<c:if test="${donorFields.firstName.hidden != true }">
				<div>
					<form:label path="firstName">${donorFields.firstName.displayName}</form:label>
					<form:input path="firstName" value="${donorFields.firstName.defaultValue}" />
					<form:errors class="formError" path="donor.firstName" delimiter=", "></form:errors>
				</div>
			</c:if>
			<c:if test="${donorFields.middleName.hidden != true }">
				<div>
					<form:label path="middleName">${donorFields.middleName.displayName}</form:label>
					<form:input path="middleName" value="${donorFields.middleName.defaultValue}" />
					<form:errors class="formError" path="donor.middleName"
						delimiter=", "></form:errors>
				</div>
			</c:if>
			<c:if test="${donorFields.lastName.hidden != true }">
				<div>
					<form:label path="lastName">${donorFields.lastName.displayName}</form:label>
					<form:input path="lastName" value="${donorFields.lastName.defaultValue}" />
					<form:errors class="formError" path="donor.lastName" delimiter=", "></form:errors>
				</div>
			</c:if>
			<c:if test="${donorFields.birthDate.hidden != true }">
				<div>
					<form:label path="birthDate">${donorFields.birthDate.displayName}</form:label>
					<form:input path="birthDate" class="birthDate"
											value="${donorFields.birthDate.defaultValue}" />
					<form:errors class="formError" path="donor.birthDate" delimiter=", "></form:errors>
				</div>
			</c:if>
			<c:if test="${donorFields.age.hidden != true }">
				<div>
					<form:label path="age">${donorFields.age.displayName}</form:label>
					<form:input path="age"
											value="${donorFields.age.defaultValue}" />
					<form:errors class="formError" path="donor.birthDateInferred" delimiter=", "></form:errors>
				</div>
			</c:if>
			<c:if test="${donorFields.gender.hidden != true }">
				<div>
					<form:label path="gender">${donorFields.gender.displayName}</form:label>
					<form:select path="gender" id="${genderSelectorId}">
						<form:option value="not_known" label="Not Known" />
						<form:option value="male" label="Male" />
						<form:option value="female" label="Female" />
						<form:option value="not_applicable" label="Not Applicable" />
					</form:select>
					<form:errors class="formError" path="donor.gender" delimiter=", "></form:errors>
				</div>
			</c:if>
			<c:if test="${donorFields.address.hidden != true }">
				<div>
					<form:label path="address" class="labelForTextArea">${donorFields.address.displayName}</form:label>
					<form:textarea path="address" />
					<form:errors class="formError" path="donor.address" delimiter=", "></form:errors>
				</div>
			</c:if>
			<c:if test="${donorFields.city.hidden != true }">
				<div>
					<form:label path="city">${donorFields.city.displayName}</form:label>
					<form:input path="city" value="${donorFields.city.defaultValue}" />
					<form:errors class="formError" path="donor.city" delimiter=", "></form:errors>
				</div>
			</c:if>
			<c:if test="${donorFields.province.hidden != true }">
				<div>
					<form:label path="province">${donorFields.province.displayName}</form:label>
					<form:input path="province" value="${donorFields.province.defaultValue}" />
					<form:errors class="formError" path="donor.province" delimiter=", "></form:errors>
				</div>
			</c:if>
			<c:if test="${donorFields.district.hidden != true }">
				<div>
					<form:label path="district">${donorFields.district.displayName}</form:label>
					<form:input path="district" value="${donorFields.district.defaultValue}" />
					<form:errors class="formError" path="donor.district" delimiter=", "></form:errors>
				</div>
			</c:if>
			<c:if test="${donorFields.state.hidden != true }">
				<div>
					<form:label path="state">${donorFields.state.displayName}</form:label>
					<form:input path="state" value="${donorFields.state.defaultValue}" />
					<form:errors class="formError" path="donor.state" delimiter=", "></form:errors>
				</div>
			</c:if>
			<c:if test="${donorFields.country.hidden != true }">
				<div>
					<form:label path="country">${donorFields.country.displayName}</form:label>
					<form:input path="country" value="${donorFields.country.defaultValue}" />
					<form:errors class="formError" path="donor.country" delimiter=", "></form:errors>
				</div>
			</c:if>
			<c:if test="${donorFields.zipcode.hidden != true }">
				<div>
					<form:label path="zipcode">${donorFields.zipcode.displayName}</form:label>
					<form:input path="zipcode" value="${donorFields.zipcode.defaultValue}" />
					<ul>
						<form:errors class="formError" path="donor.zipcode" delimiter=", "></form:errors>
					</ul>
				</div>
			</c:if>
			<c:if test="${donorFields.notes.hidden != true }">
				<div>
					<form:label path="notes" class="labelForTextArea">${donorFields.notes.displayName}</form:label>
					<form:textarea path="notes" />
					<form:errors class="formError" path="donor.notes"></form:errors>
				</div>
			</c:if>
		</form:form>
		
	
		<div style="margin-left: 200px;">
			<label></label>
			<button type="button" class="addDonorButton autoWidthButton">
				Add Donor
			</button>
			<button type="button" class="clearFormButton autoWidthButton">
				Clear form
			</button>				
		</div>
	</div>

	<div id="${childContentId}">
	</div>

</div>
