# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
	config.vm.box = "precise32"
	config.vm.box_url = "http://files.vagrantup.com/precise32.box"

	#config.vm.network :bridged
	config.vm.network  "hostonly", "192.168.33.10"
	config.vm.forward_port 80, 8080

	config.vm.share_folder "bsis", "/bsis", "../../../"

	# Ensure packages are up to date
	config.vm.provision :shell do |shell|
		shell.inline = "sudo apt-get update"
		shell.inline = "sudo apt-get install vim -y"
	end

	#Install required puppet modules
	config.vm.provision :shell do |shell|
  	    shell.inline = "mkdir -p /etc/puppet/modules;
            puppet module install puppetlabs/mysql;
            puppet module install puppetlabs/java;
            puppet module install example42/tomcat;"
 	end

	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "./"
		puppet.manifest_file  = "bsis.pp"
	end
end