# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  # Forward the default tomcat port to the host
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Sync the bsis directory to the VM
  config.vm.synced_folder "../../../", "/opt/bsis"

  # Increase the amount of memory otherwise mysql won't start
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
  end

  # Provision the box using the shell script
  config.vm.provision "shell", path: "provision.sh", privileged: false
end
