insert into User (id,username,password,firstname,isAdmin,isStaff,isActive,isDeleted) values  (1,'admin','admin321123','admin',1,1,1,0);
insert into ReportConfig (reportType,fieldNames) values('collection','collectionNo,center,site,dateCollected,sampleNo,shippingNo,donorNo,donorType,bloodGroup,rhd,comments');
insert into ReportConfig (reportType,fieldNames) values('product','productNo,collectionNo,dateCollected,productType,comments');
insert into ReportConfig (reportType,fieldNames) values('testResults','hiv,bloodGroup,collectionNo,dateTested,dateCollected,hbv,hcv,syphilis,comments');
insert into DisplayNames (formType,fieldNames) values('collection','collectionNo:,center:,site:,dateCollected:,sampleNo:,shippingNo:,donorNo:,donorType:,bloodGroup:,rhd:,tips:,comments:Comments');
insert into DisplayNames (formType,fieldNames) values('donor','donorID:,firstName:,lastName:,gender:,bloodType:,dob:,address:,age:,tips:,comments:Comments');
insert into DisplayNames (formType,fieldNames) values('testResults','collectionNo:,dateCollected:,dateTested:,hiv:,hbv:,hcv:,syphilis:,abo:,rhd:,bloodGroup:,tips:,comments:Comments');
insert into DisplayNames (formType,fieldNames) values('product','productNo:,collectionNo:,dateCollected:,productType:,bloodGroup:,tips:,comments:Comments');
insert into DisplayNames (formType,fieldNames) values('request','requestNo:,requestDate:,requiredDate:,site:,productType:,abo:,rhd:,bloodGroup:,quantity:,status:,tips:,comments:Comments');
insert into DisplayNames (formType,fieldNames) values('issue','issueDate:,issue:,issueTips:,comments:Comments');
insert into DisplayNames (formType,fieldNames) values('usage','productNo:,usageDate:,hospital:,ward:,useIndication:,tips:,comments:Comments');
insert into DisplayNames (formType,fieldNames) values('reports','inventorySummaryTips:,inventoryDetailsTips:,collectionsTips:,testResultsTips:,productsTips:,comments:Comments');
insert into RecordFieldsConfig (recordType, fieldNames) values('collection','center,site,sampleNo,shippingNo,donorNo,donorType,bloodGroup,rhd,comments');
insert into RecordFieldsConfig (recordType, fieldNames) values('donor','firstName,lastName,gender,bloodType,dateOfBirth,age,address,comments');
insert into RecordFieldsConfig (recordType, fieldNames) values('request','requestDate,requiredDate,comments');
insert into RecordFieldsConfig (recordType, fieldNames) values('usage','usageDate,hospital,ward,comments');
insert into RecordFieldsConfig (recordType, fieldNames) values ('testResult', 'collectionNumber,dateTested,hiv,hbv,hcv,syphilis');
insert into Location (locationId, name, type, isCenter, isCollectionSite, isUsageSite, isMobileSite, isDeleted, comments) values (101,'Lusaka',52,1,0,1,0,0,'comment_Lusaka'),(102,'Ndola',54,1,1,1,0,0,'comment_Ndola'),(103,'Kitwe',54,0,1,0,1,0,'comment_Kitwe'),(104,'Kabwe',51,0,0,1,1,0,'comment_Kabwe'),(105,'Chingola',52,0,1,1,1,0,'comment_Chingola'),(106,'Mufulira',52,0,0,0,1,0,'comment_Mufulira'),(107,'Livingstone',55,1,1,1,1,0,'comment_Livingstone'),(108,'Luanshya ',54,1,0,1,1,0,'comment_Luanshya '),(109,'Kasama',55,1,1,1,1,0,'comment_Kasama'),(110,'Chipata',52,1,0,0,1,0,'comment_Chipata');
insert into LocationType (locationTypeId, name, isDeleted, comments) values (51,'hospital',0,'comment_hospital'),(52,'school',0,'comment_school'),(53,'church',0,'comment_church'),(54,'mall',0,'comment_mall'),(55,'government building',0,'comment_government building');
insert into DonorType (donorType) values ("Voluntary"), ("Family"), ("Other");
insert into BloodBagType (bloodBagType) values ("Single"), ("Triple"), ("Paedi");